# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CargoOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuponDescuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_cupon', models.CharField(max_length=10)),
                ('habilitado', models.BooleanField(default=True)),
                ('numero_cupones', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosEcommerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('habilitado', models.BooleanField(default=True)),
                ('contexto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(max_length=100)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_impuesto', models.CharField(max_length=100)),
                ('abreviacion', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('habilitado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisa', models.CharField(max_length=5)),
                ('moneda', models.CharField(max_length=100)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('cargos', models.ManyToManyField(through='ecommerce.CargoOrden', to='ecommerce.Cargo')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Concepto')),
                ('cupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.CuponDescuento')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.EstadosEcommerce')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Cargo')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Deposito')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.EstadosEcommerce')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.FormaPago')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habilitado', models.BooleanField(default=True)),
                ('valido_hasta', models.DateTimeField(null=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Moneda')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoImpuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Impuestos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=3)),
                ('signo', models.CharField(max_length=1)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.TipoMovimiento'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='tipo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.TipoMovimiento'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impuestos',
            name='tipo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.TipoMovimiento'),
        ),
        migrations.AddField(
            model_name='deposito',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.EstadosEcommerce'),
        ),
        migrations.AddField(
            model_name='deposito',
            name='forma_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.FormaPago'),
        ),
        migrations.AddField(
            model_name='deposito',
            name='tipo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.TipoMovimiento'),
        ),
        migrations.AddField(
            model_name='deposito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cupondescuento',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.EstadosEcommerce'),
        ),
        migrations.AddField(
            model_name='cupondescuento',
            name='moneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Moneda'),
        ),
        migrations.AddField(
            model_name='cupondescuento',
            name='tipo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.TipoMovimiento'),
        ),
        migrations.AddField(
            model_name='cargoorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.OrdenCompra'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.EstadosEcommerce'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Producto'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='tipo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.TipoMovimiento'),
        ),
    ]
