# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuestos',
            name='habilitado',
            field=models.BooleanField(),
        ),
    ]
